
// This file was auto-generated by ML.NET Model Builder. 

using ML_Mineral_ID_ConsoleApp1;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
byte[] imageBytes = File.ReadAllBytes(@"C:\ML\Mineral_ID\Galena\00442650017011437338594.jpeg");
ML_Mineral_ID.ModelInput sampleData = new ML_Mineral_ID.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = ML_Mineral_ID.PredictAllLabels(sampleData);



Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.ReadKey();